theme: jekyll-theme-minimal
title: Candover Valley Choir
description: A non-auditioned community choir based in Hampshire, UK
google_analytics: UA-22048609-2
url: http://candovervalleychoir.co.uk
logo: choir-logo-blue.png
github:
  is_project_page: false
